### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by davixcky** [gustawho/plastweet#1]
Hola, se ve interesante este plasmoide, pero le agregaría que el login sea desde argumentos, por ejemplo:

``miPlasmoide --config @miUsuario #miContraseña
``

_Enviado desde mi Moto E (4) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gustawho** [comment]
Hola, davixcky

Antes que nada, disculpa el retraso en responder. Actualmente estoy trabajando en la sección del inicio de sesión y el método que mencionas está dentro de las consideraciones. Es posible lograrlo, que otros clientes lo hacen de maneras similares ("Twidere" para Android, por ejemplo), aunque no estoy seguro si viola los Términos impuestos por Twitter.

Aunque aún no está implementado, el proceso que probablemente será usado para este plasmoide es el que aparece en la sección de Ajustes:

1. Generar un *token* desde Plastweet
2. Iniciar sesión en Twitter (en el explorador, probablemente)
3. Autorizar la apliación
4. Regresar al plasmoide, agregar el token generado
5. Guardar los detalles de inicio de sesión

Pero, como dije, aún no es definitivo.

**Comment by davixcky** [comment]
No hay problema.

Esta interesante el plasmoide.

Developer c++, Java, Sql, C, Arduino. Programmer Junior
